SLACK_API_TOKEN: ""
MEAL_NAME: "meal"
HOST_NAME: "kndp.io"
CRONJOB_IMAGE_NAME: "ghcr.io/kndpio/kndp/slack-notify:0.1.0"
CRONJOB_SCHEDULE_TIME: "*/15 * * * *"
CRONJOB_SERVICE_ACCOUNT_NAME: "meal-sa"
CRONJOB_NAME: "slack-notify"
DEPLOYMENT_IMAGE_NAME: "ghcr.io/kndpio/kndp/slack-collector:0.1.0"
DEPLOYMENT_NAME: "slack-collector"
DEPLOYMENT_SERVICE_ACCOUNT_NAME: "meal-sa"
CONFIG_MAP_NAME: "meal-cm"
PROVIDER_CONFIG_REF_NAME: "meal-kubernetes-provider"
SLACK_NOTIFY_MESSAGE: "message text"
SLACK_COLLECTOR_MESSAGE: "message text"
SLACK_COLLECTOR_URL: "/events"
SLACK_COLLECTOR_PORT: "3000"
SLACK_ORDER_CHANNEL_ID: ""
JOB_NAME: "slack-order"
JOB_SERVICE_ACCOUNT_NAME: "meal-sa"
JOB_IMAGE_NAME: "ghcr.io/kndpio/kndp/slack-order:0.1.0"

function:
    image:
        name: ghcr.io/kndpio/kndp/meal
        tag: ""
