apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "local-repo.fullname" . }}
  labels:
    {{- include "local-repo.labels" . | nindent 4 }}
spec:

  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "local-repo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "local-repo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: local-repo
              mountPath: /storage
      volumes:
        - name: local-repo
          hostPath:
            path: /storage
            type: Directory
