apiVersion: v1
kind: Secret
metadata:
  name: {{ include "local-repo.fullname" . }} 
  namespace: {{ .Release.Namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: http://{{ include "local-repo.fullname" . }}.{{.Release.Namespace}}.svc:5000
  type: helm
  insecure: "true" 
  forceHttpBasicAuth: "true"
  enableLfs: "true" 
