apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "operator.fullname" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "operator.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: "{{ .Values.serviceAccount }}"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          volumeMounts:
            - name: clusters
              mountPath: .platform/clusters
              subPath: ./packages/stack/stack-operator/.platform/stacks
      volumes:
        - name: clusters
          hostPath:
            path: /storage
            type: Directory
