apiVersion: v2
name: kndp
description: A Helm chart for Kubernetes
type: application

version: 0.1.10

appVersion: "1.16.0"

dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: "~4.7.1"
  - name: argo-cd
    version: "~5.38.0"
    repository: https://argoproj.github.io/argo-helm
  - name: crossplane
    version: 1.13.0-rc.0.99.gf19d5d34
    repository: https://charts.crossplane.io/master/
  - name: vault
    version: "~0.25.0"
    repository: https://helm.releases.hashicorp.com
  - name: cluster-operator
    version: "~0.1.0"
    repository: file://../../../cluster/charts/cluster-operator
  - name: stack-operator
    version: "~0.1.0"
    repository: file://../../../stack/charts/stack-operator
