argo-cd:
  enabled: true
  configs:
    cm:
       ui.cssurl: "./css/generated.css"
  server:
    volumes: 
      - name: ui
        hostPath: 
          path: /storage
      - name: css
        hostPath:
          path: /storage/packages/kndp/charts/kndp/files
    volumeMounts:
      - name: ui
        mountPath: /tmp/extensions
        subPath: ./packages/kndp/charts/kndp/files
      - name: css
        mountPath: /shared/app/css
    ingress:
      enabled: true
      hosts:
        - kndp.local
      annotations: 
         kubernetes.io/ingress.class: nginx
         nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
         nginx.ingress.kubernetes.io/ssl-passthrough: "true"

ingress-nginx:
  controller:
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
    hostPort:
      enabled: true
    terminationGracePeriodSeconds: 0
    service:
      type: NodePort
    watchIngressWithoutClass: true
    nodeSelector:
      ingress-ready: "true"
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Equal"
        effect: "NoSchedule"
    publishService:
      enabled: false
    extraArgs:
      publish-status-address: localhost
      enable-ssl-passthrough: true

 
