
argo-cd:
  enabled: true
  server:
    volumes: 
      - name: ui
        hostPath: 
          path: /storage
    volumeMounts:
      - name: ui
        mountPath: /tmp/extensions
    ingress:
      annotations: 
         kubernetes.io/ingress.class: nginx

  ingress-nginx:
    controller:
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
      hostPort:
        enabled: true
      terminationGracePeriodSeconds: 0
      service:
        type: NodePort
      watchIngressWithoutClass: true

      nodeSelector:
        ingress-ready: "true"
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Equal"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Equal"
          effect: "NoSchedule"

      publishService:
        enabled: false
      extraArgs:
        publish-status-address: localhost

