apiVersion: v1
kind: ConfigMap
metadata: 
    name: {{ .Chart.Name }}-cm
data:
    SLACK_API_TOKEN: "{{ .Values.SLACK_API_TOKEN }}" 
    MEAL_NAME: "{{ .Values.MEAL_NAME }}"
    HOST_NAME: "{{ .Values.HOST_NAME }}"
    CRONJOB_IMAGE_NAME: "{{ .Values.CRONJOB_IMAGE_NAME }}"
    CRONJOB_SCHEDULE_TIME: "{{ .Values.CRONJOB_SCHEDULE_TIME }}"
    CRONJOB_SERVICE_ACCOUNT_NAME: "{{ .Values.CRONJOB_SERVICE_ACCOUNT_NAME }}"
    CRONJOB_NAME: "{{ .Values.CRONJOB_NAME }}"
    DEPLOYMENT_IMAGE_NAME: "{{ .Values.DEPLOYMENT_IMAGE_NAME }}"
    DEPLOYMENT_NAME: "{{ .Values.DEPLOYMENT_NAME }}"
    DEPLOYMENT_SERVICE_ACCOUNT_NAME: "{{ .Values.DEPLOYMENT_SERVICE_ACCOUNT_NAME }}"
    CONFIG_MAP_NAME: "{{ .Values.CONFIG_MAP_NAME }}"
    PROVIDER_CONFIG_REF_NAME: "{{ .Values.PROVIDER_CONFIG_REF_NAME }}"
    SLACK_NOTIFY_MESSAGE: "{{ .Values.SLACK_NOTIFY_MESSAGE }}"
    SLACK_COLLECTOR_MESSAGE: "{{ .Values.SLACK_COLLECTOR_MESSAGE }}"
    SLACK_COLLECTOR_URL: "{{ .Values.SLACK_COLLECTOR_URL }}"
    SLACK_COLLECTOR_PORT: "{{ .Values.SLACK_COLLECTOR_PORT }}"
    SLACK_ORDER_CHANNEL_ID: "{{ .Values.SLACK_ORDER_CHANNEL_ID }}"