apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: {{ .Chart.Name }}-function
  # annotations:
  #   render.crossplane.io/runtime: Development
spec:
  package: ghcr.io/kndpio/kndp/package:0.1.0
  runtimeConfigRef:
    name: {{ .Chart.Name }}-function-runtime
