apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: {{ .Chart.Name }}-function
  # annotations:
  #   render.crossplane.io/runtime: Development
spec:
  package: {{ .Values.function.image.name }}:{{ .Values.function.image.tag | default .Chart.AppVersion }}
  runtimeConfigRef:
    name: {{ .Chart.Name }}-function-runtime
