apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-cluster-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["*"]
- apiGroups: ["kndp.io"]
  resources: ["meals"]
  verbs: ["*"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: {{ .Chart.Name }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
