apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: operator
  name: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: operator
      containers:
      - name: operator
        image: stacks-operator:0.1.0  

        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: operator
          mountPath: "/.platform/stacks"  
        ports:
        - containerPort: 8080
      volumes:
      - name: operator
        hostPath:
          path: /storage
