apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: meal-cluster-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["*"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["*"]
- apiGroups: ["kndp.io"]
  resources: ["meals"]
  verbs: ["*"]



---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: meal-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: meal-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: meal-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: meal-cluster-role
  apiGroup: rbac.authorization.k8s.io
