apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backstage-backend.fullname" . }}
  labels:
    {{- include "backstage-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backstage-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "backstage-backend.labels" . | nindent 8 }}
	      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ .Chart.Name }}-sa
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: API_ENDPOINTS
            value: {{- .Values.apiEndpoints | join(";") -}}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
      envFrom:
      - secretRef:
          name: backstage-token