apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-cr
rules:
  - apiGroups: ['kndp.io']
    resources: ['*']
    verbs: ['get', 'list', 'watch', 'create', 'edit', 'delete']

  - apiGroups:
    - ""
    resources:
    - 'pods'
    - 'secrets'
    - 'pods/portforward'
    - 'configmaps'
    verbs:
    - '*'
  - apiGroups:
    - argoproj.io
    resources:
    - appprojects
    - applications
    verbs:
    - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-crb
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Chart.Name }}-cr
  apiGroup: rbac.authorization.k8s.io
