apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}-cr
rules:
  - apiGroups: ['kndp.io']
    resources: ['releases']
    verbs: ['get', 'list', 'watch', 'create', 'edit']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Chart.Name }}-crb
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: custom-cluster-role
  apiGroup: rbac.authorization.k8s.io
