apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: function-meal-b551b2939ded-clusterrole
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: function-meal-b551b2939ded-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: function-meal-b551b2939ded
  namespace: default
roleRef:
  kind: ClusterRole
  name: function-meal-b551b2939ded-clusterrole
  apiGroup: rbac.authorization.k8s.io
