apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-aplication-set
  annotations:
    description: "Aceasta este o descriere"
spec:
  generators:
  - list:
      elements:
      - appName: nginx-ingress-controller
        namespace: ingress-nginx
  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      source:
        repoURL: https://github.com/Timex1854/helm.git
        targetRevision: HEAD
        path: "./"
        helm:
          # Release name override (defaults to application name)
          releaseName: "{{appName}}"
          valueFiles:
          - values.yaml
      destination:
        name: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true