name: Build and Push Docker Images
on:
  push:
    branches:
      - 'release/*'

defaults:
  run:
    shell: bash
    working-directory: ./

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: extract and build
        id: build
        run: |
              git diff --name-only HEAD~1..HEAD > build.txt
              export hash=$(echo "${{ github.sha }}")
              cat build.txt | xargs -I {} dirname {} | awk -F'/' 'NF >= 2 { print $1 "/" $2 }' | uniq | xargs -I{} find {} -type f -name "Dockerfile" | xargs -I{} bash -c 'context=$(dirname "{}"); dir=$(dirname "{}" | awk -F"/" "{ print \$2 }"); docker build -t "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/$dir:$hash" "$context" && docker push "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/$dir:$hash"'
