name: Build and Push Docker Images

on:
  push:
    branches:
      - 'release/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:  
          registry: ghcr.io   
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}
  
    - name: Build OCI Images
      id: build
      run: |
        git diff --name-only HEAD~1..HEAD > build.txt
        if grep -q '/Dockerfile$' build.txt; then
          hash=$(echo ${{ github.sha }})  
          awk -F "/" '{print $1}' build.txt | uniq | xargs -I{} find {} -type d -exec sh -c 'cd "{}" && test -f Dockerfile && docker build -t "{}:${hash}" .' \;
          # Push the Docker images to GitHub Packages.
          awk -F "/" '{print $1}' build.txt | uniq | xargs -I{} docker push docker.pkg.github.com/${{ github.actor }}/{}/{}:${hash}
        else
          echo "No new Dockerfiles found, skipping Docker image build"
        fi