name: Release Charts

on:
  push:
    branches:
      - feature/KNDP-30-Helm-Charts-packaging-action

jobs:
  release:

    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: list
        run: ls -a
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: packages/kndp/charts
          config: .github/workflows/config.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

        