name: Release Charts
on:
  pull_request:
    types:
      - closed
    branches:
      - 'release/0.1'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: packages/kndp/charts

        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_GIT_REPO: helm-charts
          CR_OWNER: kndp
          CR_GIT_BASE_URL: "https://api.github.com/"
          CR_GIT_UPLOAD_URL: "https://uploads.github.com/"
          CR_SKIP_EXISTING: true


        