name: Deploy to GitHub Pages

on:
  push:
    branches: [feature/KNDP-31]   


jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18          

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npx nx run website:build     
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./website 